name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup da BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - name: Descarga de dependencias
        run: gleam deps download

      - name: Comprobacion de formato
        run: find . -type f -not -path "./build/*" -not -name "sql.gleam" -name "*.gleam" | xargs gleam format --check

      - name: Ejecucion de tests
        run: gleam test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
